### ISSUE TITLE
CSS prevents tab navigation?

### ISSUE THREAD

**Issue by axlekb** [haubek/bootstrap4c-chosen#11] opened 2019-04-11 20:26 UTC
Hi!  Thanks for doing all this work!

I was trying to keyboard navigate a form using `TAB` key, but the `chosen` input in my form was skipped over.  I was able to track the error down to the `display: none` below.  Haven't looked much into why it was styled that way, but removing it does not seem to have a visible effect.

```CSS
.chosen-container-single .chosen-search-input {
  display: none;
  border: none; }
```

**Comment by haubek** [comment] 2019-04-12 04:32
Hi @axlekb -- I had a look into this and couldn't replicate the issue. Do you mind `[Tab]` navigate through the example view (https://haubek.github.io/chosen/) to see if you still have the issue here.
It's working fine for me?!
// Martin

**Comment by axlekb** [comment] 2019-04-12 14:56
Thanks Martin, you're right, it works perfectly on on your demo site (and I actually had tested before and was baffled, but forgot to mention that when I submitted the issue).  Tabs work for me with the default chosen css, so I just started trying to isolate what in the CSS made it stop working.

In doing a deeper dive, I notice is that on your demo site, the DOM does not contain `.chosen-search-input` for any of your examples, however the [chosen-js demo site](https://harvesthq.github.io/chosen/) does, and mine does as well.  I have no idea why yours does not.


```html
<!-- DOM on https://haubek.github.io/chosen/  -->
<div class="chosen-drop">
  <div class="chosen-search">
    <input type="text" autocomplete="off">
  </div>
  <ul class="chosen-results">...</ul>
</div>
```

```html
<!-- DOM on https://harvesthq.github.io/chosen/ -->
<div class="chosen-drop">
  <div class="chosen-search">
    <input class="chosen-search-input" type="text" autocomplete="off" readonly="" tabindex="9">
  </div>
  <ul class="chosen-results">...</ul>
</div>
```

**Comment by haubek** [comment] 2019-04-15 03:08
Hi @axlekb -- Thanks for pointing me to the solution. I think the issue is fixed now by simply adding...
```css
.chosen-container-single .chosen-search-input {
  display: none;
}
```
I also added a few style improvements to the latest release.

**Closed as completed by haubek** 2019-04-15 03:08 UTC
